#!/bin/bash

function print_usage () {
	cat 1>&2 <<__EOF__
Usage: harvester [<flags>]

Flags:
      --help                     Show context-sensitive help.
  -p, --project=PROJECT          Project alias.
  -t, --time=7                   Time spent working on project.
  -d, --date=DATE                Date when work was done (e.g. 2017-01-31).
  -m, --description=DESCRIPTION  Description of work.
      --list-modules             List project sprints with IDs.
__EOF__
}

function error_flag () {
	local flag="$1"

	echo "harvester: error: required flag $flag not provided, try --help"

	exit 1
}

function hcl_log () {
	local project="$1"
	local time="$2"
	local date="$3"
	local description="$4"

	if [ -z "$project" ]; then
		error_flag '--project'
	fi

	if [ ! -z "$time" ]; then
		time="+${time}"
	fi

	hcl log "$date" "@${project}" "$time" "$description"
}

function main () {
	local project=''
	local time=''
	local date=''
	local description=''

	while [ $# -gt 0 ]; do
		case "$1" in
			-p | --project)
				project="$2"

				shift 2
				continue
				;;
			--project=*)
				project="${1##--project=}"

				shift
				continue
				;;
			-t | --time)
				time="$2"

				shift 2
				continue
				;;
			--time=*)
				time="${1##--time=}"

				shift
				continue
				;;
			-d | --date)
				date="$2"

				shift 2
				continue
				;;
			--date=*)
				date="${1##--date=}"

				shift
				continue
				;;
			-m | --description)
				description="$2"

				shift 2
				continue
				;;
			--description=*)
				description="${1##--description=}"

				shift
				continue
				;;
			--list-modules)
				shift
				continue
				;;
			--help)
				print_usage

				return 0
				;;
		esac
	done

	hcl_log "$project" "$time" "$date" "$description"
}

main "$@"
