#!/bin/bash

# Copyright (c) 2018 Teddy Wing
#
# This file is part of Harvester.
#
# Harvester is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Harvester is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Harvester. If not, see <http://www.gnu.org/licenses/>.

VERSION='0.1.0'

function print_usage () {
	cat 1>&2 <<__EOF__
Usage: harvester [<flags>]

Flags:
      --help                     Show context-sensitive help.
  -p, --project=PROJECT          Project alias.
  -t, --time=7                   Time spent working on project.
  -d, --date=DATE                Date when work was done (e.g. 2017-01-31).
  -m, --description=DESCRIPTION  Description of work.
      --list-modules             List project sprints with IDs.
      --update-module            Change the sprint of the given project.
  -v, --version                  Show application version.
__EOF__
}

function exit_with_error () {
	local message="$1"

	echo "harvester: error: $message" 1>&2

	exit 1
}

function error_flag () {
	local flag="$1"

	exit_with_error "required flag $flag not provided, try --help"
}

function hcl_log () {
	local project="$1"
	local time="$2"
	local date="$3"
	local description="$4"

	if [ -z "$project" ]; then
		error_flag '--project'
	fi

	if [ ! -z "$time" ]; then
		time="+${time}"
	fi

	hcl log "$date" "@${project}" "$time" "$description"
}

function list_modules () {
	local project="$1"

	local project_id=$(grep "$project" $HOME/.hcl/settings.yml |
		cut -d ' ' -f 2)

	hcl tasks | grep "^${project_id}"
}

function update_module () {
	local project="$1"

	if [ -z "$project" ]; then
		error_flag '--project'
	fi

	if ! command -v pick > /dev/null; then
		exit_with_error '--update-module requires `pick(1)` (https://github.com/calleerlandsson/pick)'
	fi

	module_id=$(list_modules "$project" |
		pick |
		cut -d '	' -f 1)

	if [ -z "$module_id" ]; then
		exit_with_error 'bad module ID'
	fi

	project_id="${module_id% *}"
	task_id="${module_id#* }"

	hcl unalias "$project"
	hcl alias "$project" "$project_id" "$task_id"
}

function main () {
	local project=''
	local time='7'
	local date=''
	local description=''

	while [ $# -gt 0 ]; do
		case "$1" in
			-p | --project)
				project="$2"

				shift 2
				continue
				;;
			--project=*)
				project="${1##--project=}"

				shift
				continue
				;;
			-t | --time)
				time="$2"

				shift 2
				continue
				;;
			--time=*)
				time="${1##--time=}"

				shift
				continue
				;;
			-d | --date)
				date="$2"

				shift 2
				continue
				;;
			--date=*)
				date="${1##--date=}"

				shift
				continue
				;;
			-m | --description)
				description="$2"

				shift 2
				continue
				;;
			--description=*)
				description="${1##--description=}"

				shift
				continue
				;;
			--list-modules)
				list_modules "$project"

				return 0
				;;
			--update-module)
				update_module "$project"

				return
				;;
			--help)
				print_usage

				return 0
				;;
			-v | --version)
				echo $VERSION

				return 0
				;;
		esac
	done

	hcl_log "$project" "$time" "$date" "$description"
}

main "$@"
